### ISSUE TITLE
italic font style

### ISSUE THREAD

**Issue by adiraoco** [siteorigin/settings#1]
The fonts settings adds `font-style: italic;`, irrespective of whether the font variant is italic or not. This occurs only in the front end. All's well in the customizer.

FYI. This also seems to be a bug in the recent update to SiteOrigin North.

**Comment by adiraoco** [comment]
Changing `-1` to `false` [here](https://github.com/siteorigin/settings/blob/develop/settings.php#L679) should do the trick.

**Comment by gregpriday** [comment]
That line is technically correct, but there must be something else in there causing a problem. I'll investigate this now.

**Comment by gregpriday** [comment]
Aaah, never mind. You were right. Fixing this up.

**Comment by gregpriday** [comment]
Fixed with https://github.com/siteorigin/settings/commit/000b22c92826dac85d2e54c25b6e1df9391a5769
