### ISSUE TITLE
Page Settings breaks Customizer when moving between archive types.

### ISSUE THREAD

**Issue by adiraoco** [siteorigin/settings#16]
Suppose I have a archive page open (let's say a Monthly Archive) and I have the page settings open.  From a post in the archive suppose I click on a post's author, I go to the author's archive. But the customizer turns blank like so: 

![customizer-setting-bug](https://cloud.githubusercontent.com/assets/3372029/15942832/d2849f0e-2ea3-11e6-8eaa-51881b0341c2.png)

**Comment by Misplon** [comment]
Ahh nice catch @adiraomj. I'm sure @gregpriday can check this out later.
