### ISSUE TITLE
Changing theme in the customizer

### ISSUE THREAD

**Issue by adiraoco** [siteorigin/settings#2]
Just noticed that when the live preview of another theme is chosen in Customizer, the settings from the presently active theme are displayed for settings that are common in both themes.

( Noticed this in the case of logo for North and Unwind )

P.S. Not sure if this is an issue with my local setup. Let me know if it is.

**Comment by gregpriday** [comment]
I wonder if that's a desirable feature. Although it's probably something we'd need to take into account. Make sure that there aren't setting names that clash.

**Comment by adiraoco** [comment]
How about adding a prefix to all panel id's with the theme name to avoid clashing with future themes? 
Like `branding` to `unwind_branding`. 

Or do we add it to fields that are likely to clash? 
Like `logo` to `unwind_logo` and `accent` to `unwind_accent`. 

Please advise.

**Comment by gregpriday** [comment]
I'll take a look at this and see if it's a major issue and if there might be an easier way to fix it. I don't really want to prefix the settings because they're already prefixed in the database, so that would be doubling up a bit.

**Comment by Misplon** [comment]
@gregpriday Any further thoughts here?
