### ISSUE TITLE
Live preview in Child Theme

### ISSUE THREAD

**Issue by adiraoco** [siteorigin/settings#20]
I was working on a child theme for North and noticed that the customizer live preview did not seem to work.

**Comment by Misplon** [comment]
@adiraomj Is there perhaps something specific to this site causing the problem. Here is a North child I worked on last week. All seems ok.

![se](https://cloud.githubusercontent.com/assets/789159/17099281/ad947c36-5267-11e6-9bec-05182791bf9e.png)

**Comment by adiraoco** [comment]
@Misplon have a look at any color setting under **Theme Settings**. Ideally, the color on the site should change as you change the color. Let me know if this does not happen to you. 

I have not checked all the fields, only noticed it on color field.

**Comment by Misplon** [comment]
Ahh sorry man, thought you meant the entire preview.

Confirmed. I actually need to refresh the Customizer to see color changes. Saving and Publishing isn't enough.

**Comment by adiraoco** [comment]
Sorry. Should have been more specific. :)

**Comment by Misplon** [comment]
Nah all good. Makes total sense now.

**Comment by AlexGStapleton** [comment]
Can confirm. Issue seems to be that trying to output the files as if they were in the child theme directly, likely due to get_stylesheet_directory_uri().

![](https://i.imgur.com/28aj7HN.png)
