### ISSUE TITLE
Defaults aren't saving

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/settings#23]
The Vantage issue, #siteorigin/vantage/issues/165 (Mobile Menu: Setting enabled by default but not visible until setting resaved in an odd manner) is a widespread issue with the bulk of our themes. We need to ensure that defaults are saved to avoid issues like this happening.

**Comment by gregpriday** [comment]
I'll take a look. This might have something to do with how settings were migrated from our old settings framework to the new one.

**Comment by gregpriday** [comment]
Aaah, so it looks like the defaults were being initialized too late, on `init`, while Vantage was using them on `after_setup_theme`. So a little too late.

**Comment by AlexGStapleton** [comment]
Awesome - thanks mate! :)
