### ISSUE TITLE
When viewing a page template setting, if you navigate away the custimizer contents will be hidden

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/settings#24]
The title is likely awful so please refer to the gif for a full explanation. Basically, if I open up a page template settings group, for example blog, and then open a blog page. It'll hide the customizer contents. Which prevents me from going up a menu. The only solution to resolve this is to reopen the blog page or close the customizer.

Blank Customizer:
![](https://i.imgur.com/l1Wx4y0.png)

Reference GIF:
![](https://i.imgur.com/CFwJm5L.gif)

**Comment by Misplon** [comment]
Thanks dude. Definitely needs sorting. Logged here: https://github.com/siteorigin/settings/issues/16.
