### ISSUE TITLE
Error while compiling settings CSS

### ISSUE THREAD

**Issue by adiraoco** [siteorigin/settings#3]
I am recieving this error while running `./create-css.php`

```
Error: Base-level rules cannot contain the parent-selector-referencing character '&'.
        on line 26 of /private/var/folders/3s/6ts826px2fz6rnbvlsx8frpr0000gn/T/bVflT3/sass/mixins/css3/_selection.scss, in `selection'
        from line 43 of /private/var/folders/3s/6ts826px2fz6rnbvlsx8frpr0000gn/T/bVflT3/sass/elements/_elements.scss
        from line 62 of /private/var/folders/3s/6ts826px2fz6rnbvlsx8frpr0000gn/T/bVflT3/sass/style.scss
  Use --trace for backtrace.
```

**Comment by gregpriday** [comment]
Are you still getting this error? That's an error straight from the SCSS compiler. Although the way we're doing variable injection might be causing some problems.

**Comment by adiraoco** [comment]
It was still a problem the last time I  checked. 

To avoid the error I have done https://github.com/siteorigin/siteorigin-north/blob/develop/sass/elements/_elements.scss#L50-L58 instead of using the mixin.

**Comment by Misplon** [comment]
@gregpriday has this been resolved?

**Comment by Misplon** [comment]
Closing for the moment as a limitation. Can look at it later if NB.
