### ISSUE TITLE
Fonts Selector: Add an active default selection

### ISSUE THREAD

**Issue by Misplon** [siteorigin/settings#30]
If possible, ensure the font selector shows the default value.

![defaults](https://cloud.githubusercontent.com/assets/789159/19601565/2a4605ec-97aa-11e6-8680-219b8e3b71b3.png)

**Comment by Misplon** [comment]
Still a challenge. Thanks.

**Comment by gregpriday** [comment]
This would be a tricky one to fix. Basically we're using _blank_ to let our CSS generation know that it shouldn't output anything and just rely on what the theme is defining.

We could have it check if the current value for any font field is equal to the default value and have it strip out settings that haven't changed. This would require quite a few changes that might break other things. Not worth the risk.

**Comment by Misplon** [comment]
No problem, thanks for taking a look.
