### ISSUE TITLE
Page Settings: Improve WooCommerce support

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/settings#33]
Based on siteorigin/vantage#205

WooCommerce changes the shop page to an archive page (which IS controllable via the page template settings) which prevents the page settings from working. [Andrew has suggested](https://siteorigin.slack.com/archives/themes/p1478772867000346) that we should add a conditional for this page as well as any other page to better support this.

**Comment by Misplon** [comment]
Being that it is technically an archive page, I think we should disable page settings for WooCommerce shop.

**Comment by AlexGStapleton** [comment]
That might confuse people as it's not exactly obvious that it's an archive. Regardless, that would likely be the easiest method for us. Maybe we could add a message or something and state the the user is trying to edit an archive - that'll avoid the confusion.
