### ISSUE TITLE
siteorigin_page_setting values for main shop template

### ISSUE THREAD

**Issue by adiraoco** [siteorigin/settings#35]
`siteorigin_page_setting` returns only the default values for the main shop template. i.e., the template that return true for `is_shop()`.

**Comment by AlexGStapleton** [comment]
Wait. Is this kind of like the issue I just posted #36?

**Comment by Misplon** [comment]
@adiraomj Would it be possible to please, provide a use case for this issue?

**Comment by Misplon** [comment]
@adiraomj A quick reminder. If able, can you provide us with some more details on this issue?
