### ISSUE TITLE
siteorigin_page_setting(): Work out post specific settings when called

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/settings#36]
Create a page and set it to not display the post title. Add a post loop widget and select a template like content-single.php in Vantage, or template-parts/content-single.php in North - it must use the same post specific settings.

The settings for the last post in the post loop will be used for the main page. This means that the post title on the main page will be displayed.

[Reference layout](https://u.teknik.io/ldc7M.json).

**Comment by Misplon** [comment]
I've removed all non-loops from the Post Loop widget so hopefully, that helps this.
