### ISSUE TITLE
It's impossible to change the priority of sections.

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/settings#37]
[This line](https://github.com/siteorigin/settings/blame/develop/settings.php#L477) uses $id in a calculation but the issue here is that all of our themes don't set the id to a number (it's text). This means that it's actually impossible to change the priority without directly adjusting the placement of a section in the settings array as the priority is always set to 10 (as $id will result in 0 - it'll always be 0 + 10).

It might be a good idea to introduce an optional priority field.

**Comment by gregpriday** [comment]
I think this was resolved by https://github.com/siteorigin/settings/commit/3d18ac5b3d92c0bae3cad43505176691a5450512, which just means settings sections are given a priority that corresponds to the order in which they were added.
