### ISSUE TITLE
Add current value to range slider

### ISSUE THREAD

**Issue by Misplon** [siteorigin/settings#4]
If possible, add the current value to our new range slider. Below is an example from Kirki:

![slider](https://cloud.githubusercontent.com/assets/789159/14896435/03328f54-0d7e-11e6-8c26-89223966da4b.png)

https://kirki.org/docs/controls/slider.html

We could also consider adding the reset button Kirki has next to the current value to allow users to return to the theme default. I think the addition of these two would make our range slider awesome :) Thanks @gregpriday.

**Comment by Misplon** [comment]
@gregpriday below is where we currently are:

<img width="274" alt="current-slider" src="https://cloud.githubusercontent.com/assets/789159/14896498/53373fcc-0d7e-11e6-9d44-1d54527d8e6b.png">

**Comment by gregpriday** [comment]
We're using the core WordPress range slider control here. Not sure if this is possible with what they've provided. This might be possible with a small hack, but those sorts of hacks don't tend to work across versions.

With our theme's focus on light weight options panels, I'd like to use as many core fields as possible.

**Comment by Misplon** [comment]
Cool, agreed. Thanks for checking.
