### ISSUE TITLE
Multiple placeholders should be ordered

### ISSUE THREAD

**Issue by Misplon** [siteorigin/settings#44]
Multiple placeholders should be ordered. Expected '%1$s, %2$s, %3$s, %4$s', but got %s, %s, %s, %s
In inc/settings/inc/about_page.php line 36 and inc/settings/inc/upgrade.php line 50

@gregpriday This came up in the Corp review. Can you attend for us?

**Comment by gregpriday** [comment]
Resolved with https://github.com/siteorigin/settings/commit/bce7361a9d74180c17f9a73971d1009895e353b4
