### ISSUE TITLE
Prepare Settings for WordPress 5.0

### ISSUE THREAD

**Issue by Misplon** [siteorigin/settings#48]
Prep the theme settings framework for WP 5.0.

**Comment by AlexGStapleton** [comment]
The Page Settings metabox appears to work without issue with Gutenberg after the recent change to the SiteOrigin Widgets Bundle (related to `wp_reset_query`). The only issue I can see is that page setting changes aren't reflected in the preview so you have to save the page to view what the resulting changes are.

**Comment by Misplon** [comment]
@AlexGStapleton Chatted with Braam, please could you attend.

**Comment by AlexGStapleton** [comment]
I've looked into the previously highlighted point and this is a known Gutenberg issue. https://github.com/WordPress/gutenberg/issues/11280

@Misplon Have you come across any other issues? I just did another general run through and didn't experience any issues (outside of the preview issue).

**Comment by Misplon** [comment]
Not at this time. Thanks for taking a look.

**Comment by Misplon** [comment]
@AlexGStapleton Can you please take a look at the compatibility flags we need added for 5.0: https://make.wordpress.org/core/2018/11/07/meta-box-compatibility-flags/

**Comment by AlexGStapleton** [comment]
Those flags are actively ignored for themes.

https://github.com/WordPress/wordpress-develop/blob/5.0/src/wp-admin/includes/template.php#L1111-L1132

Looking into our plugins now.
