### ISSUE TITLE
Block Editor: Resolve styling differences

### ISSUE THREAD

**Issue by Misplon** [siteorigin/settings#54]
The Block Editor isn't rendering our settings in quite the same way. I've made a few small fixes for the Vantage specific settings but to fix the Page Settings we'd need to make a change here. I'm not sure if it'll get fixed in the core or not.

![Add_New_Page_‹_SiteOrigin_—_WordPress](https://user-images.githubusercontent.com/789159/79488903-c6bcfa00-801a-11ea-97c8-8a182002687e.png)

**Comment by AlexGStapleton** [comment]
The spacing between settings and setting colors difference are due to [this](https://github.com/WordPress/WordPress/blob/5.7/wp-includes/css/dist/edit-post/style.css). That file is only being loaded in the Block Editor so would be intentional.
