### ISSUE TITLE
SCSS rgba and variables

### ISSUE THREAD

**Issue by adiraoco** [siteorigin/settings#7]
I updated the settings submodule in North and then generated the settings css. I dont think the scss variables are being replaced with the settings variables at instances where rgba is being used in the SCSS. Can you please have a look.

**Comment by adiraoco** [comment]
The variables problem seems have sorted itself out. No idea why it was misbehaving for a little while. Sorry guys.

**Comment by Misplon** [comment]
Sweet, glad it came right. No worries.
