### ISSUE TITLE
Create Widget Field

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/settings#8]
This is something we had in the original settings framework. It should be fairly easy to adapt into the new Customizer based settings.

https://github.com/siteorigin/extras/blob/develop/settings/settings.php#L524
https://github.com/siteorigin/extras/blob/develop/settings/js/settings.js#L216

**Comment by Misplon** [comment]
@gregpriday Think I saw this in Influence. Cool to close?

**Comment by gregpriday** [comment]
Resolved with https://github.com/siteorigin/settings/commit/a76ca2ac294674b5cf31050ac0dca29c6c5cdf4b
